### ISSUE TITLE
calculate_velocities inverts velocity direction

### ISSUE THREAD

**Issue by leoli51** [GDQuest/godot-steering-ai-framework#40]
https://github.com/GDQuest/godot-steering-ai-framework/blob/beca7b9cc7b43fd2c1cf948a6c263a92ec4175d5/project/src/Agents/GSAIKinematicBody2DAgent.gd#L131

Hi
I have an agent (the enemy) pursuing the player , when the distance is under a certain threshold 
the enemy should stop and then dash the player. 
I noticed that when the enemy has to stop it suddenly flips the velocity's direction.
Note: the enemy code didn't apply a behaviour for a frame (so the velocity is calculated by the formula)
I think there is an error in the formula to calculate the velocity of the agent if no behaviour was applied in the last frame. Shouldn't it be current_pos - last_pos ?

the library is wonderful and very useful thanks! <3

**Comment by NathanLovato** [comment]
I will let @Razoric480 check this. It might be helpful if you could share your code, so Razoric can see what you are calling and how.

**Comment by Razoric480** [comment]
I've recreated the issue on this end, and yeah, you're right, the _last_position and current_position should be inverted. Pushing a fix now.
