### ISSUE TITLE
Looking to contribute: I am basically finished porting this repo to Godot 4.1.1

### ISSUE THREAD

**Issue by daneehAI** [GDQuest/godot-steering-ai-framework#61]
Hi! 

As the title says, I ported this repo to Godot 4.1.1.

There don't seem to be any unit tests etc; but the code conversion was mostly a matter of swapping out deprecated datatypes for new ones and updating the syntax here and there.

The Arrive3d demo scene required some tinkering with rotations and shape parameters as well as lighting to make it look like the Godot 3 version as closely as possible.

Scaling of 2D scenes is still a bit broken, but I think I'll be able to fix that tomorrow.

Please let me know how to proceed after that! Do I just make a pull request that a GDQuest team member then checks?

Kind regards,
Dani

**Comment by NathanLovato** [comment]
Thanks much for taking the time to do this, Dani! Absolutely, please feel free to open a PR, we'll check it out and merge once it's ready!

**Comment by daneehAI** [comment]
Will do! I noticed that the framework submodules have a separate repo that is referenced by this repo. As I said, I'm working out some kinks with the demo scenes, but the AI code seems to be working perfectly. Shall I open a pull request for that on that repo?

**Comment by NathanLovato** [comment]
Yes, please feel free to push all the changes to this repository. I think we can drop the submodule copy and instead keep everything in a single repository, for easier access and maintenance. These days, we have several Godot package managers to pick from that are far more efficient than using git submodules, like [gd-plug](https://github.com/imjp94/gd-plug) for example. This one automatically extracts just the addon portion of the repository into your Godot projects, and keeps it and all your addons up to date with a single command.

**Comment by daneehAI** [comment]
Okay, I'll just use this repo then!
